name: Stock Analyzer CI

on:
  push:
    branches: [ main ] # Or your default branch
    paths:
      - 'stock_analyzer/**' # Only run on changes within the stock_analyzer directory
  pull_request:
    branches: [ main ] # Or your default branch
    paths:
      - 'stock_analyzer/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./stock_analyzer # Set working directory for all run steps

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or your preferred Node.js version
        cache: 'npm' # Or 'yarn', 'pnpm'
        cache-dependency-path: stock_analyzer/package.json # Or yarn.lock, etc. - Assumes package.json is in stock_analyzer

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Lint code
      run: |
        echo "Linting step placeholder. Configure your linter (e.g., ESLint, Stylelint)."
        # Example: npx eslint . --ext .ts,.tsx
        # Example: npx stylelint "**/*.css"

    - name: Type check
      run: npm run typecheck

    - name: Build project
      run: npm run build

    - name: Prepare deployment package
      run: |
        mkdir -p staging_dir/dist
        cp -r dist/* staging_dir/dist/
        cp index.html staging_dir/
        cp index.css staging_dir/
        cp sw.js staging_dir/
        cp manifest.json staging_dir/
      working-directory: ./stock_analyzer

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire staging directory
        path: ./stock_analyzer/staging_dir # Path is relative to GITHUB_WORKSPACE

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
