name: Stock Analyzer CI

on:
  push:
    branches: [ main ] # Or your default branch
    paths:
      - 'stock_analyzer/**' # Only run on changes within the stock_analyzer directory
  pull_request:
    branches: [ main ] # Or your default branch
    paths:
      - 'stock_analyzer/**'

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./stock_analyzer # Set working directory for all run steps

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or your preferred Node.js version
        cache: 'npm' # Or 'yarn', 'pnpm'
        cache-dependency-path: stock_analyzer/package.json # Or yarn.lock, etc. - Assumes package.json is in stock_analyzer

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Lint code
      run: |
        echo "Linting step placeholder. Configure your linter (e.g., ESLint, Stylelint)."
        # Example: npx eslint . --ext .ts,.tsx
        # Example: npx stylelint "**/*.css"

    - name: Type check
      run: npm run typecheck

    - name: Build project
      run: npm run build

    # Add a step to upload build artifacts if needed for deployment
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: stock-analyzer-build
        path: stock_analyzer/dist/ # Or wherever your build output is
