/**
 * A service class for interacting with the GitHub API.
 * On every load it first reads the local data.json file (updated by CI on every
 * push / merge / rebase) to detect whether a new commit has landed since the
 * last cache write. If so the cache is invalidated and fresh data is fetched
 * from the GitHub API, ensuring the page always reflects the current repository
 * state.
 */
class GitHubService {
    #owner;
    #repo;
    #url;
    #dataJsonUrl;
    #cache;
    #stateManager;

    /**
     * @param {string} owner - The owner of the repository.
     * @param {string} repo - The name of the repository.
     */
    constructor(owner, repo) {
        this.#owner = owner;
        this.#repo = repo;
        this.#url = `https://api.github.com/repos/${this.#owner}/${this.#repo}/commits?per_page=10`;
        // data.json lives in the same directory as index.html.
        this.#dataJsonUrl = './data.json';
        this.#cache = new CacheService();
        this.#stateManager = StateManager.getInstance();
    }

    /**
     * Tries to fetch the local data.json file which is regenerated by CI on
     * every push/merge/rebase. Returns the parsed object, or null on failure.
     * @private
     */
    async #fetchDataJson() {
        try {
            const response = await fetch(this.#dataJsonUrl + '?_=' + Date.now(), { cache: 'no-store' });
            if (!response.ok) return null;
            return await response.json();
        } catch {
            return null;
        }
    }

    /**
     * Fetches the latest commits and updates the central state.
     * Always checks data.json first to surface the most recently updated site
     * and to invalidate the IndexedDB cache when a new commit is detected.
     */
    async fetchLatestCommits() {
        this.#stateManager.setState({ isLoading: true, error: null });
        try {
            // Step 1: read the CI-generated data.json for the latest commit SHA
            // and the most recently changed site URL.
            const dataJson = await this.#fetchDataJson();
            if (dataJson) {
                this.#stateManager.setState({ latestSite: dataJson });
            }

            // Step 2: decide whether the cache is still valid.
            const cachedData = await this.#cache.getCachedCommits();
            const latestSha = dataJson && dataJson.latestSha;

            const cacheHasLatest = cachedData && latestSha &&
                cachedData.some(c => c.sha === latestSha);

            if (cachedData && cachedData.length > 0 && (!latestSha || cacheHasLatest)) {
                console.log("Loading commits from cache.");
                const commits = Commit.fromApiData(cachedData);
                this.#stateManager.setState({ commits, isLoading: false });
                return;
            }

            // Step 3: cache is stale or empty — fetch fresh data from GitHub API.
            if (cachedData) {
                console.log("New commit detected; clearing stale cache.");
                await this.#cache.clearCache();
            }

            console.log("Fetching fresh data from the GitHub API.");
            const response = await fetch(this.#url);
            if (!response.ok) {
                throw new Error(`GitHub API error: ${response.status}`);
            }
            const data = await response.json();

            await this.#cache.cacheCommits(data);
            const commits = Commit.fromApiData(data);
            this.#stateManager.setState({ commits, isLoading: false });

        } catch (error) {
            console.error("Error fetching or caching commits:", error);
            this.#stateManager.setState({ isLoading: false, error: "Failed to fetch commits. Please try again later." });
        }
    }
}
