name: Daily Click Analytics Report

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: python -m pip install pandas

    - name: Download analytics data
      run: curl -o click_data.csv 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSJnM65In6d7mwude3S9mZG6xgKdtjqs-PP9XEKZxfyKPjYABvyZvOoCZjThzi036xbaoM7zSshbZXY/pub?output=csv'

    - name: Generate Analytics Report
      run: python generate_report.py

    - name: Commit and push report
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "docs: update daily click analytics report"
        file_pattern: CLICK_ANALYTICS.md
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"