name: Manage .dat Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  manage_dat_files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Move .dat files
        run: |
          mkdir -p serverroom/store/db
          mv serverroom/*.dat serverroom/store/db/ || echo "No .dat files to move"

      - name: Run build script
        run: python serverroom/build.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated: Move .dat files and update files.json"
          branch: main
          file_pattern: "serverroom/store/db/*.dat serverroom/store/files.json"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"