name: Menus CI
on:
  push:
    branches: [ main ]
    paths:
    - 'menus/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'menus/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
      working-directory: ./menus
    - name: Run webpack build
      run: npm run build
      working-directory: ./menus
