name: Web Scraping Action

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r jscript/requirements.txt

    - name: Run scraper
      run: python jscript/scrape_website.py

    - name: Move and rename database
      run: mv finance.db.gz scrape/finance.db.gz

    - name: Commit and push database
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add scrape/finance.db.gz
        git commit -m "Update scraped financial data" || echo "No changes to commit"
        git push
