name: Web Scraping Action

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r jscript/requirements.txt

    - name: Run scraper
      run: python jscript/scrape_website.py
